#!/bin/env bash

usbcheck(){ \
    mounteddrives="$(lsblk -rpo "name,type,size,mountpoint" | grep -v 'nvme' | awk '$2=="part"&&$4!=""{printf "%s (%s)\t  ",$1,$3}')"
    if [ $(echo "$mounteddrives" | wc -w) -gt 0 ]; then
        echo "  $mounteddrives"
    else
        if [ $(echo "$usbdrives" | wc -w) -gt 0 ]; then
            echo " "
        else
            echo ""
        fi
    fi
}

mountusb(){ \
    chosen=$(echo "$usbdrives" | rofi -dmenu -show run -lines 5 -opacity "85" -bw 0 -width 30 -padding 20 -i -p "¿Qué unidad quieres montar?" | awk '{print $1}')
    mountpoint=$(udisksctl mount --no-user-interaction -b "$chosen" 2>/dev/null | sed 's/Mounted/Montado/g' | sed 's/at/en/g') && dunstify -i usb "Montando Unidad" "$mountpoint
" && exit 0
}

umountusb(){ \
    chosen=$(echo "$mounteddrives" | rofi -dmenu -show run -lines 5 -opacity "85" -bw 0 -width 30 -padding 20 -i -p "¿Qué unidad quieres desmontar?" | awk '{print $1}')
    mountpoint=$(udisksctl unmount --no-user-interaction -b "$chosen" 2>/dev/null) && dunstify -i usb "Desmontando Unidad" "$chosen desmontado" && exit 0
    udisksctl power-off --no-user-interaction -b "$chosen"
}

umountall(){ \
    for chosen in $(echo $(lsblk -rpo "name,type,size,mountpoint" | grep -v 'nvme' | awk '$2=="part"&&$4!=""{printf "%s\n",$1}')); do
        udisksctl unmount --no-user-interaction -b "$chosen"
        udisksctl power-off --no-user-interaction -b "$chosen"
    done
}


usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | grep -v 'nvme' | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')"
mounteddrives="$(lsblk -rpo "name,type,size,mountpoint" | grep -v 'nvme' | awk '$2=="part"&&$4!=""{printf "%s (%s)\n",$1,$3}')"

case "$1" in
    --check)
        usbcheck
        ;;
    --mount)
        if [ $(echo "$usbdrives" | wc -w) -gt 0 ]; then
            # dunstify -i usb "USB detectado(s)"
            mountusb
        else
            dunstify -i usb "No se ha detectado ninguna unidad USB sin montar" && exit
        fi
        ;;
    --umount)
        if [ $(echo "$mounteddrives" | wc -w) -gt 0 ]; then
            # dunstify -i usb "USB detectado(s)"
            umountusb
        else
            dunstify -i usb "No existen unidades USB para desmontar" && exit
        fi
        ;;
    --umount-all)
        if [ $(echo "$mounteddrives" | wc -w) -gt 0 ]; then
            dunstify -i usb "Todas las unidades USB han sido desmontadas"
            umountall
        else
            dunstify -i usb "No existen unidades USB para desmontar" && exit
        fi
        ;;
esac
